# Generated by Django 3.0.4 on 2020-03-19 22:45

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('posts', '0002_posts_featured'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
